### ISSUE TITLE
Build+run instructions not working

### ISSUE THREAD

**Issue by kentcb** [fsprojects/fantomas-tools#266]
Hi,

I want to get this building and running locally, but not having any luck. Following the instructions in the README leads to missing `.deps`:

```
FSC : error FS0225: Source file 'C:\Users\Kent\Repository\fantomas-tools\src\server\TriviaViewer\../../../.deps/fantomas/src/Fantomas/RangeHelpers.fs' could not be found [C:\Users\Kent\Repository\fantomas-tools\src\server\TriviaViewer\TriviaViewer.fsproj]
```

What's the recommended way to set up dependencies? I hacked it to work a few days back by editing the solution and project files, but ultimately still ran into an issue. I run into the same issue when running via Gitpod, which is that `localhost:9060` does not respond after starting.

Any ideas what I'm doing wrong?

**Comment by nojaf** [comment]
Hey, could you try running `dotnet fake run build.fsx -t "Fantomas-Git"` first?
That should clone the Fantomas repo in the `.deps` folder.
This should happen automatically in Gitpod because of https://github.com/fsprojects/fantomas-tools/blob/1a6484941e2b146bcf0b6fc6aa64c8ff54272d95/.gitpod.yml#L8.
And it does take a while before all is restored.

I just tried this myself and was able to run everything in a fresh gitpod workspace.
Again, it does take a while so all components to be in place, so I also got the initial `9060` isn't doing anything and I had to refresh a moment later.

**Comment by kentcb** [comment]
Sorry, got taken out by Pfizer 2.0 for a few days 👊🤕

Running the `Fantomas-Git` target first certainly fills in the dependencies - thanks. Unfortunately, still doesn't run locally but I see this in the output of `dotnet fake run build.fsx -t Watch`, which seems relevant:

```
yarn run v1.22.11
$ vite
'vite' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
```

I'm not proficient in node/yarn/JS/whatever the hell this is, so will need to look into this separately.

As for the gitpod, I feel like I must be doing something wrong. Even opening the gitpod gives me an immediate error in the terminal:

![image](https://user-images.githubusercontent.com/1901832/127971661-4d8d56b3-3910-4e65-b7ba-af4ebbd1b4ea.png)

Ignoring that, `dotnet tool restore` also fails:

![image](https://user-images.githubusercontent.com/1901832/127971800-72bac20a-2d56-43e0-87be-4a76683347ff.png)

🤔

**Comment by kentcb** [comment]
OK, I got it to run locally. I had to run `yarn` on its own inside `clientDir` so that packages were restored _before_ `yarn start` was called.

**Comment by nojaf** [comment]
> 'vite' is not recognized as an internal or external command,
This is indicating that `yarn` did not restore the `node_modules`.
I would expect this to happen when you ran `dotnet fake run build.fsx -t Install`, this should trigger the target `YarnInstall` as well.
Do you have yarn `1.x` installed? This project is still using [yarn 1](https://classic.yarnpkg.com/en/docs/install#windows-stable).

All in all, to get everything running there are a lot of moving pieces so that is why gitpod is so appealing here.
I'm not sure why you are getting this aggregation exception. Are you start a new workspace from this repo or a fork?

**Comment by nojaf** [comment]
> OK, I got it to run locally.

Aha, that is good news.

**Comment by kentcb** [comment]
btw, happy to PR appropriate changes to fix all this once I collate and understand them all. I'll keep a list here:

- Running locally:
  - `dotnet fake run build.fsx -t "Fantomas-Git"`
  - run `yarn` in the client source dir (presumably should be added to the FAKE script)
- Running via gitpod:
  - ?

**Comment by nojaf** [comment]
The yarn target does exist, what happens when you run `dotnet fake run build.fsx -t YarnInstall`?

https://github.com/fsprojects/fantomas-tools/blob/9d6c2fe67fbd13fd93968afb355f1fcdd2f2040d/build.fsx#L147

**Comment by kentcb** [comment]
> Are you start a new workspace from this repo or a fork?

It's from this repo using [this link](https://gitpod.io/#https://github.com/fsprojects/fantomas-tools). I just tried stopping the workspace and starting again, even though I think that shouldn't be necessary. It didn't make any difference - same error. Are you saying you don't see that error in terminal as soon as you open the gitpod?

**Comment by nojaf** [comment]
Stopping and starting won't fix anything, but what happens if you run a completely new workspace?
This honestly worked without a problem last week for me.

**Comment by kentcb** [comment]
> what happens if you run a completely new workspace?

Even if I explicitly request a new workspace via the gitpod dashboard, the problem reproduces for me. Looks like [I'm not the only one to hit this](https://community.gitpod.io/t/cannot-run-dotnet-tool-restore/4388), so maybe a recent gitpod change has broken things.

**Comment by nojaf** [comment]
Interesting, it seems like `dotnet tool restore` is no longer working in gitpod.
```
gitpod /workspace/fantomas-tools $ dotnet tool restore
System.AggregateException: One or more errors occurred. (No such file or directory) (No such file or directory) (No such file or directory) (No such file or directory)
 ---> System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute(Action`1 processStarted)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Tool.Install.ProjectRestorer.Restore(FilePath project, PackageLocation packageLocation, String verbosity)
   at Microsoft.DotNet.ToolPackage.ToolPackageInstaller.InstallPackageToExternalManagedLocation(PackageLocation packageLocation, PackageId packageId, VersionRange versionRange, String targetFramework, String verbosity)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.<>c__DisplayClass11_0.<Execute>b__0(ToolManifestPackage package)
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   at System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.SpoolingTask.SpoolStopAndGo[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, SynchronousChannel`1[] channels, TaskScheduler taskScheduler)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.ExecuteAndGetResultsAsArray()
   at System.Linq.ParallelEnumerable.ToArray[TSource](ParallelQuery`1 source)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.Execute()
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
   at Microsoft.DotNet.Tools.Tool.ToolCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
 ---> (Inner Exception #1) System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute(Action`1 processStarted)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Tool.Install.ProjectRestorer.Restore(FilePath project, PackageLocation packageLocation, String verbosity)
   at Microsoft.DotNet.ToolPackage.ToolPackageInstaller.InstallPackageToExternalManagedLocation(PackageLocation packageLocation, PackageId packageId, VersionRange versionRange, String targetFramework, String verbosity)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.<>c__DisplayClass11_0.<Execute>b__0(ToolManifestPackage package)
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   at System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)<---

 ---> (Inner Exception #2) System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute(Action`1 processStarted)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Tool.Install.ProjectRestorer.Restore(FilePath project, PackageLocation packageLocation, String verbosity)
   at Microsoft.DotNet.ToolPackage.ToolPackageInstaller.InstallPackageToExternalManagedLocation(PackageLocation packageLocation, PackageId packageId, VersionRange versionRange, String targetFramework, String verbosity)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.<>c__DisplayClass11_0.<Execute>b__0(ToolManifestPackage package)
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   at System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)<---

 ---> (Inner Exception #3) System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute(Action`1 processStarted)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Tool.Install.ProjectRestorer.Restore(FilePath project, PackageLocation packageLocation, String verbosity)
   at Microsoft.DotNet.ToolPackage.ToolPackageInstaller.InstallPackageToExternalManagedLocation(PackageLocation packageLocation, PackageId packageId, VersionRange versionRange, String targetFramework, String verbosity)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.<>c__DisplayClass11_0.<Execute>b__0(ToolManifestPackage package)
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   at System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)<---
```
so this indicates that something may have changed on gitpod side.

**Comment by nojaf** [comment]
Ok, I see you found your way as well to https://community.gitpod.io/t/cannot-run-dotnet-tool-restore/4388

**Comment by nojaf** [comment]
Hey @kentcb, after many many changes, this is now back in a state where this should work in gitpod.
Would you mind trying it out for me?

**Comment by kentcb** [comment]
Hmm, upon loading a fresh workspace I get this in terminal output:

```
 HISTFILE=/workspace/.gitpod/cmd-1 history -r; {
rm paket-files/ -rf && dotnet tool restore && dotnet fake run build.fsx -t Install -p 2
}
gitpod /workspace/fantomas-tools (master) $  HISTFILE=/workspace/.gitpod/cmd-1 history -r; {
> rm paket-files/ -rf && dotnet tool restore && dotnet fake run build.fsx -t Install -p 2
> }

Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.200

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
/home/gitpod/dotnet/sdk/6.0.200/NuGet.targets(564,5): error : The process cannot access the file '/home/gitpod/.nuget/NuGet/nugetorgadd.trk' because it is being used by another process. [/tmp/p3igyfvl.sdf/restore.csproj]
/home/gitpod/dotnet/sdk/6.0.200/NuGet.targets(564,5): error : The process cannot access the file '/home/gitpod/.nuget/NuGet/nugetorgadd.trk' because it is being used by another process. [/tmp/1tporrbi.hpe/restore.csproj]

Package "paket" failed to restore, due to Microsoft.DotNet.ToolPackage.ToolPackageException: The tool package could not be restored.
   at Microsoft.DotNet.Tools.Tool.Install.ProjectRestorer.Restore(FilePath project, PackageLocation packageLocation, String verbosity)
   at Microsoft.DotNet.ToolPackage.ToolPackageInstaller.InstallPackageToExternalManagedLocation(PackageLocation packageLocation, PackageId packageId, VersionRange versionRange, String targetFramework, String verbosity)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)
Package "fake-cli" failed to restore, due to Microsoft.DotNet.ToolPackage.ToolPackageException: The tool package could not be restored.
   at Microsoft.DotNet.Tools.Tool.Install.ProjectRestorer.Restore(FilePath project, PackageLocation packageLocation, String verbosity)
   at Microsoft.DotNet.ToolPackage.ToolPackageInstaller.InstallPackageToExternalManagedLocation(PackageLocation packageLocation, PackageId packageId, VersionRange versionRange, String targetFramework, String verbosity)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)

Tool 'fable' (version '3.7.1') was restored. Available commands: fable
Tool 'fantomas-tool' (version '4.7.0') was restored. Available commands: fantomas

Restore partially failed.
```

But, strangely, `paket` _does_ appear to be installed:

```
gitpod /workspace/fantomas-tools (master) $ dotnet tool list
Package Id         Version             Commands      Manifest                                           
--------------------------------------------------------------------------------------------------------
paket              7.0.0-alpha018      paket         /workspace/fantomas-tools/.config/dotnet-tools.json
fake-cli           5.22.0              fake          /workspace/fantomas-tools/.config/dotnet-tools.json
fable              3.7.1               fable         /workspace/fantomas-tools/.config/dotnet-tools.json
fantomas-tool      4.7.0               fantomas      /workspace/fantomas-tools/.config/dotnet-tools.json
```

Moreover, a subsequent `dotnet tool restore` works fine:

```
gitpod /workspace/fantomas-tools (master) $ dotnet tool restore
Tool 'paket' (version '7.0.0-alpha018') was restored. Available commands: paket
Tool 'fake-cli' (version '5.22.0') was restored. Available commands: fake
Tool 'fable' (version '3.7.1') was restored. Available commands: fable
Tool 'fantomas-tool' (version '4.7.0') was restored. Available commands: fantomas

Restore was successful.
```

Finally, `dotnet fantomas .` does indeed work:

```
gitpod /workspace/fantomas-tools (master) $ dotnet fantomas .
Processing ./build.fsx
./build.fsx has been written.
```

So I think we're good on the gitpod front. As for the original issue, tbh I've forgotten some of the context, but I think it came down to gaps in the docs per [this](https://github.com/fsprojects/fantomas-tools/issues/266#issuecomment-891598598)?

Thanks for following up, @nojaf.

**Comment by nojaf** [comment]
So for the Gitpod part, I'd say close enough 🙈.
As for the original issue, I believe the gaps in the documentation are also solved now.
What is now in https://github.com/fsprojects/fantomas-tools#running-in-gitpod will do the trick I think.
The markdown could use an extra blank line between the commands but content-wise should be ok.

**Comment by kentcb** [comment]
Great, thanks @nojaf
